#!/usr/bin/env python3
"""Bygg metodrapportens aktuella resultat från sparad OCR-export."""
import argparse,datetime,html,json,re
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('corpus',type=Path);a=p.parse_args();root=Path(__file__).resolve().parents[1];site=root/'docs';docs=json.loads((site/'assets/pilot.js').read_text().split(' = ',1)[1].rstrip(';\n'))['documents'];quality=json.loads((site/'ocr-quality.json').read_text());progress=json.loads((a.corpus/'04_metadata/ocr_batch_progress.json').read_text());benchmark=json.loads((site/'ocr-benchmark.json').read_text());corefile=a.corpus/'04_metadata/ocr_core_progress.json';core=json.loads(corefile.read_text()) if corefile.exists() else {};coreCandidates=list((a.corpus/'02_ocr/tesseract-core-v4').glob('*/*.json'));core=dict(version='core-v4',available=len(coreCandidates),planned=core.get('planned',218),latestRun=core if core.get('updatedAt','')>=progress['startedAt'] else None);now=datetime.datetime.now(datetime.timezone.utc).isoformat();totals=dict(pdfDocuments=len(docs),pdfPages=sum(d['pages'] for d in docs),rawTextPages=sum(d['rawTextPages'] for d in docs),searchTextPages=sum(d['textPages'] for d in docs),**quality['stats']);totals['remainingWithoutSearchText']=totals['pdfPages']-totals['searchTextPages'];archive=a.corpus/'04_metadata/ocr_runs_before_statistics_fix';history=[json.loads(f.read_text()) for f in sorted(archive.glob('*.json'))] if archive.exists() else []
tailfile=a.corpus/'04_metadata/ocr_tail_progress.json';tail=json.loads(tailfile.read_text()) if tailfile.exists() else {};tail=tail if tail.get('startedAt','')>=progress['startedAt'] else {}
report=dict(schemaVersion=1,tail=tail,priorRuns=history,updatedAt=now,timeBudgetHours=10,totals=totals,batch=progress,core=core,benchmark=benchmark,policy='Maskinell screening och OCR; manuella revisioner har företräde. Alla OCR-kandidater är ogranskade. Säkerhetsvärde mäter inte faktisk korrekthet.')
(site/'bulk-processing.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(a.corpus/'04_metadata/bulk_processing_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
f=lambda n:format(n,',').replace(',',' ')
rows=[('PDF-sidor kontrollerade och grundextraherade',totals['pdfPages']),('Sidor med ursprungligt textlager',totals['rawTextPages']),('Sidor med ny OCR-kandidat',totals['processed']),('Nya OCR-kandidater som passerade söktextregeln',totals['chosen']),('Tidigare textlösa sidor som fått söktext',totals['filled']),('Sidor med söktext efter bearbetningen',totals['searchTextPages']),('Sidor utan vald söktext',totals['remainingWithoutSearchText']),('OCR-sidor med maskinsäkerhet under 85',totals['lowConfidence'])]
body='<p>Uppdaterad '+html.escape(now[:19].replace('T',' '))+' UTC. Körningens status: '+html.escape({'complete':'slutförd','running':'pågår','budget-stopped':'avbruten vid tidsgränsen'}.get(progress['state'],progress['state']))+'.</p><table><caption>Bearbetningens omfattning</caption><thead><tr><th scope="col">Mått</th><th scope="col">Antal PDF-sidor</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+label+'</th><td>'+f(n)+'</td></tr>' for label,n in rows)+'</tbody></table>'
body+='<p>Kärnverken har '+f(core['available'])+' av '+f(core['planned'])+' kandidater i den korrigerade versionen. </p>'
body+='<p>Den korrigerade huvudkörningen tog '+f(round(progress['elapsedSeconds']/60))+' minuter och redovisar '+str(len(progress['errors']))+' tekniska fel. Start och senaste tidpunkt samt eventuell tidsavbruten bearbetning finns i körningsrapporten. Den separata kärnkörningen redovisas därutöver; körtider överlappar och ska inte summeras som total väggtid.</p>'
body+='<p>Metodtestet använder 3 293 referensord från de tio tidigare AI-assisterat granskade sidorna. Ordfelsmåttet räknar insättningar, bortfall, felläsningar och fel ordning efter gemener och borttagen interpunktion. Extra OCR från illustrationer kan höja värdet. Arbetsfacit är inte oberoende dubbelgranskat, urvalet är litet och resultaten gäller inte hela korpusen.</p>'
methods=[('Ursprungligt textlager',benchmark['rawWordErrorRate']),('Första testet, manuellt förberedda sidhalvor',next(m['wordErrorRate'] for m in benchmark['methods'] if m['psm']==3)),('Masskörningens automatiska metod',benchmark.get('pipelineCorrected',benchmark['pipeline'])['wordErrorRate'])]
if 'coreCalibrationV4' in benchmark:methods.append(('Kalibrerad kärnmetod för Kinberg och Handlingar',benchmark['coreCalibrationV4']['wordErrorRate']))
body+='<table><caption>Ordfelsmått på arbetsfacit</caption><thead><tr><th scope="col">Textversion</th><th scope="col">Ordfelsmått</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+label+'</th><td>'+format(rate*100,'.1f').replace('.',',')+' %</td></tr>' for label,rate in methods)+'</tbody></table><p>Tabeller och bilder ger stora skillnader mellan metoder, även när säkerhetsvärdet är högt. Parametrarna har kalibrerats på samma arbetsfacit; detta är metodutveckling, inte ett oberoende kvalitetstest. De korrekturlästa texterna används fortsatt för dessa tio sidor.</p><p><a href="bulk-processing.json" download>Hämta körningsrapport och metodtest</a> · <a href="ocr-quality.json" download>Hämta prioriterad granskningskö</a> · <a href="quality-screening.json" download>Hämta screening av alla PDF-sidor</a> · <a href="bulk-validation.json" download>Hämta integritetskontrollen</a></p>'
p=site/'index.html';s=p.read_text();s=re.sub(r'<div id="bulk-results">.*?</div>',lambda m:'<div id="bulk-results">'+body+'</div>',s,flags=re.S);p.write_text(s)
print(json.dumps(totals,ensure_ascii=False))
